# ██████╗ ███████╗ █████╗ ██╗     ███╗   ███╗███████╗
# ██╔══██╗██╔════╝██╔══██╗██║     ████╗ ████║██╔════╝
# ██████╔╝█████╗  ███████║██║     ██╔████╔██║███████╗
# ██╔══██╗██╔══╝  ██╔══██║██║     ██║╚██╔╝██║╚════██║
# ██║  ██║███████╗██║  ██║███████╗██║ ╚═╝ ██║███████║
# ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚══════╝╚═╝     ╚═╝╚══════╝
# A plugin adding Feudalism to minecraft using Bukkit. Developed by Traffic and Jena-bot.

