main: main.realms.java.RealmsMain
version: 0.2.0
name: Realms
api-version: 1.16
authors:
  - Jena-bot
  - Traffic
load: POSTWORLD

permissions:
  realms.command.*:
    children:
      - realms.command.status
      - realms.command.land

  realms.command.status:
    description: allows players to check a person's status.

  realms.command.land:
    description: allows players to check a land's status;
